### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by pearlheartgtr** [lucashuguet/Microsoft-Rewards-Bot#1]
This is the error I get:

Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
ERROR: Could not find a version that satisfies the requirement pickle (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for pickle (from -r requirements.txt (line 2))

And this when I try to run app.py:
Traceback (most recent call last):
  File "C:\Users\...l\Desktop\Microsoft-Rewards-Bot-master\app.py", line 36, in <module>
    app = getJSON('./passwd.json')
  File "C:\Users\...\Desktop\Microsoft-Rewards-Bot-master\app.py", line 34, in getJSON
    return json.load(fp)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 20 (char 68)

**Comment by lucashuguet** [comment]
I am looking for a solution to this problem. When I find it I will commit.
Thanks for the report :)
PS: I'm french so sorry for my english.

**Comment by lucashuguet** [comment]
I fix the issue with pickle but the second its because your .passwd.json is bad.
Could you 
Can you share your .passwd.json (by hiding passwords and emails)?

**Comment by pearlheartgtr** [comment]
Here it is:

{
    "accounts":[
        {
            "id":1,
            "name":<one>,
            "email":"------",
            "passwd":"-----"
        },
        {
            "id":2,
            "name":<two>,
            "email":"------",
            "passwd": "------"
        },
        {
            "id":3,
            "name":<three>,
            "email":"-----",
            "passwd": "-------"
        }

    ]
}

**Comment by lucashuguet** [comment]
Did you leave the name section **black** ? Because your error tell: error l.5. And line 5 u leave blank the name section. Try this:

```json
{
    "accounts":[
        {
            "id":1,
            "name":,
            "email":"------",
            "passwd":"-----"
        },
        {
            "id":2,
            "name": "-----",
            "email":"------",
            "passwd": "------"
        },
        {
            "id":3,
            "name": "-----",
            "email":"-----",
            "passwd": "-------"
        }
    ]
}
```

**Comment by pearlheartgtr** [comment]
No, the name wasn't blank. But that all seems to be fixed. 

But there's another problem with the chrome webdriver. I keep getting "sudo is not recognized" when I try to install it. There's a driver folder with chrome in it, but I still get this error when I try to run app.py:

Traceback (most recent call last):
  File "C:\Users\...\Desktop\Microsoft-Rewards-Bot-master\app.py", line 63, in <module>
    cookie_saver(email, passwd, name, nhd)
  File "C:\Users\...\Desktop\Microsoft-Rewards-Bot-master\src\cookie_saver.py", line 24, in cookie_saver
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chrome_options)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\...\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

And yes, I downloaded the updated package.

**Comment by lucashuguet** [comment]
It's because this chromedriver is only compatible with linux. I'm working on a windows compability.

**Comment by lucashuguet** [comment]
Everything is now normally okay

**Comment by pearlheartgtr** [comment]
Thanks!

Got a couple more errors:

Traceback (most recent call last):
  File "C:\Users\...\Desktop\Microsoft-Rewards-Bot-master 1\app.py", line 64, in <module>
    mobile(name, nhd, 22)
  File "C:\Users\...\Desktop\Microsoft-Rewards-Bot-master 1\src\mobile.py", line 31, in mobile
    if(platform == "linux" or platform == "linux2" or platform == "linux3"):
NameError: name 'platform' is not defined

**Comment by lucashuguet** [comment]
It was a stupid error. That's normally fixed :disappointed_relieved:

**Comment by lucashuguet** [comment]
Does it works for you ?

**Comment by pearlheartgtr** [comment]
I just ran it and the Edge searches (20 points) and the 50 point quizzes aren't working. Other than that, everything else seems to be working.

**Comment by lucashuguet** [comment]
This bot just does the research. You earn 150 points when you are at level 2. The bot will soon be able to do everything (research and quiz). And will start automatically.

**Comment by pearlheartgtr** [comment]
Actually, I am at level 2.
